# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.gitlab.com/bill-board/bb-app-client
  tag:
  pullPolicy: Always
  secrets:
    - name: gitlab-registry

podAnnotations: {}
application:
  track: stable
  tier: web
  secretName:
  secretChecksum:
gitlab:
  app:
  env:
service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: http://buildboard.tv/
  additionalHosts:
  commonName:
  externalPort: 80
  internalPort: 80
ingress:
  tls:
    enabled: true
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 6m


