image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  KUBERNETES_VERSION: 1.12.6
  HELM_VERSION: 2.13.1
  ROLLOUT_RESOURCE_TYPE: deployment
  CI_REGISTRY_BASE_URL: registry.gitlab.com/bill-board/bb-app-client
  CI_IMAGE_TAG: $CI_PIPELINE_ID.$CI_COMMIT_SHORT_SHA

stages:
  - build
  - packaging
  - production

include:
  - local: '/pipeline-jobs/Deploy.gitlab-ci.yml'

yarn-build:
  image: node:12-slim
  stage: build
  before_script:
    - apt-get update -qq && apt-get install
    - yarn install
  script:
    - REACT_APP_API_PATH=api yarn build
    - tar -czvf build.tar -C build/ .
  artifacts:
    expire_in: 1 week
    paths:
      - $CI_PROJECT_DIR/build.tar

create-images:
  stage: packaging
  when: on_success
  only:
    - master
    - tags
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --build-arg VERSION=$CI_IMAGE_TAG -t $CI_REGISTRY_BASE_URL:$CI_IMAGE_TAG $CI_PROJECT_DIR/.
    - docker push $CI_REGISTRY_BASE_URL
