// tslint:disable
/**
 * Buildboard Campaign Publishing platform
 * Buildboard server API spec
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@buildboard.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
